name: deploy
on:
  push:
    branches:
      - master
jobs:
  delpoy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # https://github.com/marketplace/actions/github-action-for-yarn
      - name: Install packages
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # https://davidyang2149.dev/front-end/github-actions%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-gh-pages-%EC%9E%90%EB%8F%99-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
